upd for 3ds page
rbkmoney/docs pull request #151
Opened 2021-08-30 14:09 UTC by OlgaKartashevaRBK

https://rbkmoney.atlassian.net/browse/BUSINESS-176

**preview**
https://github.com/rbkmoney/docs/blob/ft/upd-for-3ds-page/content/docs/payments/3ds/index.md

**scheme**
https://github.com/rbkmoney/docs/tree/ft/upd-for-3ds-page/content/docs/payments/3ds/img

2021-08-31 15:45 UTC, volkov-sergei approved these changes

2021-09-01 08:35 UTC, yeskin approved these changes

2021-09-01 08:42 UTC, tolkonepiu requested changes

2021-09-01 08:42 UTC, tolkonepiu commented on content/docs/payments/3ds/index.md
> +    По-умолчанию все платежи,  проводимые RBK.money, требуют использования 3DS. Для уточнения возможности отключения 3DS (использования не-3DS терминала) обратитесь в службу поддержки. Однако в некот
```suggestion
    По-умолчанию все платежи, проводимые RBK.money, требуют использования 3DS. Для уточнения возможности отключения 3DS (использования не-3DS терминала) обратитесь в службу поддержки. Однако в некоторых случаях при проведении платежей через не-3DS терминал банк-эмитент всё же может потребовать аутентификацию: ваше приложение должно поддерживать использование данной технологии.
```

2021-09-01 08:42 UTC, tolkonepiu commented on content/docs/payments/3ds/index.md
> +    curl "https://3ds-mock.rbkmoney.com/mpi/acs" --data "TermUrl=https://wrapper.rbk.money&PaReq=paReq&MD=COM_MPICOM_MPI-ymJorPXs5A1"
```suggestion
    curl "https://3ds-mock.rbkmoney.com/mpi/acs" --data "TermUrl=https://wrapper.rbk.money?PaReq=paReq&MD=COM_MPICOM_MPI-ymJorPXs5A1"
```

2021-09-01 08:42 UTC, tolkonepiu commented on content/docs/payments/3ds/index.md
> +        Для того чтобы узнать об успешном прохождении [покупателем](https://developer.rbk.money/docs/payments/overview/#shop) 3DS-аутентификации, при выполнении [запроса](https://developer.rbk.money/
Не для этого. Параметр нужен для редиректа обратно на форму мерчанта после 3ds. Это справедливо даже для неуспешного прохождения 3ds.

2021-09-01 08:42 UTC, tolkonepiu commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
Лучше ждать Payment, когда он перейдет в статусы processed или failed. Инвойс так четко не отражает момент того, что авторизация прошла успешно.

Что значит:
```
RBK.money следует [опрашивать]
```

, звучит так, как будто мы опрашиваем что-то

2021-09-01 08:42 UTC, volkov-sergei submitted a review, later dismissed

2021-09-01 08:47 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +        Для того чтобы узнать об успешном прохождении [покупателем](https://developer.rbk.money/docs/payments/overview/#shop) 3DS-аутентификации, при выполнении [запроса](https://developer.rbk.money/
Есть ли у мерчант способ однозначно понять успешность 3ds?

2021-09-01 08:56 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
Давай напишу:
"[Платформу](https://developer.rbk.money/docs/payments/overview/#_1) следует опрашивать до тех пор, пока..."
?

2021-09-01 09:25 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
> Лучше ждать Payment, когда он перейдет в статусы processed или failed. Инвойс так четко не отражает момент того, что авторизация прошла успешно.

Здесь пока не совсем ясно. processed - промежуточный статус, failed - финальный неуспешный. Как они могут говорить о том, что авторизация прошла успешно? 
+ здесь я наверно привозу для консультации @keynslug, так как с ним ранее обсуждали, что по сути именно отсутсвие необходимости совершать какие-либо события **с платежом** (насколько поняла Андрея это вроде как про события с платежом, но просто запихнули в getInvoiceEvents) говорит о том, что все ок: https://developer.rbk.money/docs/payments/overview/#payScheme.

@keynslug как в итоге советуешь указать?

2021-09-01 09:41 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
Ну в случае оплаты картами processed по идее означает _как минимум_ получение авторизации эквайера.

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/img/3ds.txt
> +Client->Issuer: 5) 2factor auth code
(ИМХО) Немного неаккуратно `2factor` выглядит. Быть может по-русски `второй фактор аутентификации (код в sms)`, ну или по-английски `2FA code`?

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +    По-умолчанию все платежи, проводимые RBK.money, требуют использования 3DS. Для уточнения возможности отключения 3DS (использования не-3DS терминала) обратитесь в службу поддержки. Однако в некото
```suggestion
    По умолчанию все платежи, проводимые RBK.money, требуют использования 3DS. Для уточнения возможности отключения 3DS (использования не-3DS терминала) обратитесь в службу поддержки. Однако в некоторых случаях при проведении платежей через не-3DS терминал банк-эмитент всё же может потребовать аутентификацию: ваше приложение должно поддерживать использование данной технологии.
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +Этап, на котором используется 3DS, отражён в [данном](https://developer.rbk.money/docs/payments/overview/#payScheme) сценарии.
Быть может?
```suggestion
Этап проведения платежа, на котором используется 3DS, отражён в [данном](https://developer.rbk.money/docs/payments/overview/#payScheme) сценарии.
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +    В случае использования одной из [тестовых карт](/refs/testcards/) платформа эмулирует процесс прохождения 3DS-аутентификации.
```suggestion
    В случае использования одной из [тестовых карт](/refs/testcards/) при оплате в тестовом магазине платформа эмулирует процесс прохождения 3DS-аутентификации.
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +        * Тип переадресации `request` → `requestType` (GET или POST) зависит от решения банка-эквайера. Следует поддерживать оба варианта.
Мне кажется так будет проще / понятнее для потенциальных разрабов, которые с JS / JSON хоть отдалённо знакомы.
```suggestion
        * Тип переадресации `request.requestType` (GET или POST) зависит от решения банка-эквайера. Следует поддерживать оба варианта. 
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +        * Набор параметров в `form` для `requestType:POST` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику
Я бы предложил тут как в спеке написать тип запроса.
```suggestion
        * Набор параметров в `form` для `requestType` = `BrowserPostRequest` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику работы приложения: например, проверять наличие определённого параметра или присутствие его значения. Количество параметров и их значения при выполнении переадресации должны оставаться неизменны.
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +        * Набор параметров в `form` для `requestType:POST` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику
Кстати, нельзя ли что-то про МПС в интро написать, чтобы здесь не пришлось вот это «далее по тексту» оставлять. И ещё кстати: далее по тексту МПС нигде не встречается. 🌝

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
Согласен с @tolkonepiu: если мы говорим про интеграцию уровня платёжной формы, то ей скорее надо `InvoicePaymentStatusChanged` ждать.

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +* [Платформа](https://developer.rbk.money/docs/payments/overview/#_1) проверит необходимость использования 3DS и вернет нужные для этого данные в случае положительного результата: см. в [ответе](http
Быть может как-то так? 🤔 Чисто предложение.
```suggestion
* [Платформа](https://developer.rbk.money/docs/payments/overview/#_1) проверит необходимость использования 3DS и вернет нужные для этого данные в случае положительного результата: в ответе на [запрос событий по инвойсу](https://developer.rbk.money/api/#operation/getInvoiceEvents) появится изменение с `changeType` = `PaymentInteractionRequested` и `userInteraction.interactionType` = `Redirect`.
```

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +    Пример запроса:
Может уточнить, что это запрос средтвами curl согласно примеру ответа на getInvoiceEvents выше? 🤔

2021-09-01 10:55 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +* Покупатель воспользуется вторым фактором аутентификации на странице банка-эмитента.
Быть может просто?
```suggestion
* Покупатель введёт второй фактор аутентификации на странице банка-эмитента.
```

2021-09-01 11:02 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
А в итоге будет ли корректным/правильным с твоей точки зрения убрать информацию о том, что партнеру необходимо опираться на getInvoiceEvents для понимания, что платежом все финально ок (а значит и 3ds тоже был ок) или нужно вместо этого указать что базироваться стоит на get status (или webhook по платежу)? Или какое-то комбо предложить)

2021-09-01 11:04 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/img/3ds.txt
> +Client->Issuer: 5) 2factor auth code
да, исправлю

2021-09-01 11:08 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +        * Набор параметров в `form` для `requestType:POST` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику
Если видишь цель для обозначения МПС во вступлении - напиши, мне пока неясно)
Кажется, здесь достаточно написать "его возвращает соответствующая международная платежная система (МПС)"

2021-09-01 11:14 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
ей - МПС?) 

Мы здесь пишем чего ждать мерчу в случае, когда он отправил пользователя во время платежа на 3ds)
И так как схему мы начали с getInvoiceEvents, то и закончить ее нужно как минимум getInvoiceEvents (здесь - детализация куска общей схемы проведения платежа, на которую ссылаемся). 

В целом, именно текстом могу сослаться на общую схему и еще раз подсветить, что "у пользователя все с платежом успешно", когда статус = ?? <здесь вопрос к вам, пишем про "ы процессе" или "финальный успешный">

2021-09-01 11:17 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +    Пример запроса:
да, ок

2021-09-01 11:19 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +* Покупатель воспользуется вторым фактором аутентификации на странице банка-эмитента.
да, ок

2021-09-01 11:23 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +    В случае использования одной из [тестовых карт](/refs/testcards/) платформа эмулирует процесс прохождения 3DS-аутентификации.
да, ок, сразу коммит не делаю, хочу сделать вот так:
"при оплате в т[естовом магазине](https://help.rbkmoney.com/lk/lk/#testManagement)"

2021-09-01 11:54 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +        * Набор параметров в `form` для `requestType:POST` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику
> По-умолчанию все платежи, проводимые RBK.money, требуют использования 3DS.

Ну например вот здесь про то, что это не наши требования, а требования, налагаемые на нас МПС.

Но это чисто предложение. Учитывая, что МПС больше нигде не встречается в тексте, можно сокращение и не вводить.

2021-09-01 11:57 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
> ей - МПС?)

Платёжной форме же. )

> закончить ее нужно как минимум getInvoiceEvents

Всегда пожалуйста, мы же говорим о том, какой именно _ивент_ в ответе на getInvoiceEvents нужно дождаться.

> здесь вопрос к вам, пишем про "в процессе" или "финальный успешный", на каком в итоге базируемся

Processed − для нас имеет смысл «обработан», если ты про него.

2021-09-01 13:17 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +        * Набор параметров в `form` для `requestType:POST` может меняться: его возвращает соответствующая международная платежная система (далее по тексту —  МПС). Не следует базировать на нём логику
да, здесь укажу, что это требования МПС

2021-09-01 13:42 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
В итоге речь о том, что внутри самого события есть статус платежа и на схеме, а также текстом стоит уточнить, что вот на это и стоит обращать внимание. 
Речь была не о том, чтобы отдельно использовать запрос на получение статуса платежа после получения `InvoiceStatusChanged`

2021-09-01 13:43 UTC, OlgaKartashevaRBK commented on content/docs/payments/3ds/index.md
> +RBK.money следует [опрашивать](https://developer.rbk.money/api/#operation/getInvoiceEvents) до тех пор, пока параметр `changeType` не примет значение `InvoiceStatusChanged`. Данное значение говорит о
Итог: https://github.com/rbkmoney/docs/pull/151#discussion_r700226080

2021-09-01 13:47 UTC, OlgaKartashevaRBK commented
Проговорили с @keynslug что на схеме можно как-то отобразить уточнить, что после п6) мы переадресовываем браузер покупателя на redirectUrl мерчанта

2021-09-01 13:55 UTC, tolkonepiu commented on content/docs/payments/3ds/index.md
> +        Для того чтобы узнать об успешном прохождении [покупателем](https://developer.rbk.money/docs/payments/overview/#shop) 3DS-аутентификации, при выполнении [запроса](https://developer.rbk.money/
Только по неуспешности платежа

2021-09-02 07:14 UTC, OlgaKartashevaRBK commented
@yeskin @rbkmoney/infosec подскажите плз, есть ли какие-то комменты (помимо тех, что уже обсудили с Пашей и Андреем)?

2021-09-06 07:12 UTC, OlgaKartashevaRBK commented
@keynslug @tolkonepiu внесла изменения согласно комментариям, посмотрите плз

2021-09-06 12:05 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +[Событие](https://developer.rbk.money/docs/payments/overview/#_1) `PaymentStatusChanged` говорит об изменении состояния оплаты и соответственно статусе прохождения 3DS (см. параметр `status`):
```suggestion
[Событие](https://developer.rbk.money/docs/payments/overview/#_1) `PaymentStatusChanged` говорит об изменении состояния оплаты и, соответственно, о статусе прохождения 3DS (см. параметр `status`):
```

2021-09-06 12:05 UTC, keynslug commented on content/docs/payments/3ds/index.md
> +* `processed` и `captured` — оплату [заказа](https://developer.rbk.money/docs/payments/overview/#invoice) можно считать успешно выполненной: денежные средства в размере суммы [выставленного счета](ht
Тогда вот так по идее будет наиболее корректно:

```suggestion
* `processed` — оплату [заказа](https://developer.rbk.money/docs/payments/overview/#invoice) можно считать успешно выполненной: денежные средства в размере суммы [выставленного счета](https://developer.rbk.money/docs/payments/overview/#invoice) уже как минимум заблокированы на источнике денежных средств [плательщика](https://developer.rbk.money/docs/payments/overview/#shop);
```

2021-09-06 13:00 UTC, keynslug approved these changes

2021-09-06 16:56 UTC, vulnbe approved these changes

2021-09-08 09:13 UTC, tolkonepiu approved these changes

2021-09-08 10:06 UTC, merged